Update app.yml

diff --git a/.github/workflows/app.yml b/.github/workflows/app.yml
--- a/.github/workflows/app.yml
+++ b/.github/workflows/app.yml
@@ -23,15 +23,15 @@ jobs:
         node-version: ${{ matrix.node-version }}
         cache: 'npm'
     
-    - run: npm ci
-    - run: npm run build --if-present
-    - run: npm test
+    - name: Install Dependencies
+      run: npm ci
 
-    # Build the React app
+    - name: Run Tests
+      run: npm test
+
     - name: Build React App
       run: npm run build
 
-    # Transfer the build directory to your EC2 instance
     - name: Deploy to EC2
       env:
         EC2_IP: ${{ secrets.EC2_IP }}
@@ -41,39 +41,49 @@ jobs:
         chmod 600 private_key.pem
         scp -o StrictHostKeyChecking=no -i private_key.pem -r ./build ubuntu@$EC2_IP:/var/www/react-app
 
-    # Install and configure Nginx to serve your app
     - name: Install and Configure Nginx
       env:
         EC2_IP: ${{ secrets.EC2_IP }}
         PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
       run: |
-        ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@$EC2_IP <<-EOF
+        echo "$PRIVATE_KEY" > private_key.pem
+        chmod 600 private_key.pem
+        ssh -o StrictHostKeyChecking=no -T -i private_key.pem ubuntu@$EC2_IP <<-EOF
+          while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
+              echo "Waiting for other software managers to finish..."
+              sleep 10
+          done
+
           sudo apt update
-          sudo apt install nginx -y
+          sudo apt install -y nginx
           sudo systemctl start nginx
           sudo systemctl enable nginx
-          # Remove the default Nginx configuration
-          sudo rm /etc/nginx/sites-enabled/default
-          # Add your custom configuration
+
+          sudo rm -f /etc/nginx/sites-enabled/default
+
           echo "server {
               listen 80;
               server_name $EC2_IP;
 
               location / {
                   root /var/www/react-app;
-                  index index.html index.htm;
-                  try_files \$uri /index.html;
+                  index index.html;
+                  try_files \$uri \$uri/ /index.html;
               }
           }" | sudo tee /etc/nginx/sites-available/react-app
-          sudo ln -s /etc/nginx/sites-available/react-app /etc/nginx/sites-enabled/react-app
-          sudo nginx -t
-          sudo systemctl restart nginx
+
+          sudo ln -sf /etc/nginx/sites-available/react-app /etc/nginx/sites-enabled/
+          if sudo nginx -t; then
+              sudo systemctl restart nginx
+              echo "Nginx is reloaded successfully"
+          else
+              echo "Nginx configuration error"
+              exit 1
+          fi
         EOF
 
-    # Check the deployment status
     - name: Check Deployment
       env:
         EC2_IP: ${{ secrets.EC2_IP }}
       run: |
         echo "Visit http://$EC2_IP to see your deployed React application."
-
